services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - CONEXION=mongodb://db:27017/

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
